### ISSUE TITLE
Wrong score calculation

### ISSUE THREAD

**Issue by nielsproest** [failbreak/Blackjack#1]
In: https://github.com/failbreak/Blackjack/blob/ec805f525afb1910abacadfdc5ee3278ac9e07cc/blackjack.js#L37 the max score is 10, so J,Q, and K have the same value in the scoreboard

**Comment by failbreak** [comment]
![image](https://github.com/failbreak/Blackjack/assets/69219123/f68c0d70-5a4c-4f9f-bbb0-15d38f7a621e)
